# Generated by Django 5.0.2 on 2024-06-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concerts',
            new_name='Concert',
        ),
    ]
