# Generated by Django 5.0.2 on 2024-07-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("concerts", "0003_concert_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(editable=False, max_length=32)),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=40)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                ("town_or_city", models.CharField(max_length=40)),
                ("street_address1", models.CharField(max_length=80)),
                (
                    "street_address2",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("county", models.CharField(blank=True, max_length=80, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "order_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "concertitem_total",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=6),
                ),
                (
                    "concert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concerts.concert",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concertitems",
                        to="checkout.order",
                    ),
                ),
            ],
        ),
    ]
