# Generated by Django 5.0.2 on 2024-07-01 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
        ("concerts", "0003_concert_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderLineItem",
            new_name="OrderConcertItem",
        ),
    ]
