# Generated by Django 5.0.2 on 2024-07-02 15:22

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_rename_orderlineitem_orderconcertitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=80),
        ),
    ]
