# Generated by Django 5.0.2 on 2024-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0004_alter_order_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=40),
        ),
    ]
